FROM arm64v8/alpine

# Install Python 3 and pip in Alpine
RUN apk add --no-cache python3 py3-pip && \
    python3 -m ensurepip && \
    pip3 install --no-cache --upgrade pip

# Install webssh via pip
RUN pip3 install --no-cache webssh

# Expose the necessary port
EXPOSE 8080

# Command to run the webssh server
CMD ["wssh", "--address=0.0.0.0", "--port=8080"]
