FROM arm64v8/alpine

# Install Python 3, pip, and virtualenv
RUN apk add --no-cache python3 py3-pip py3-virtualenv

# Create a virtual environment
RUN python3 -m venv /opt/venv

# Activate the virtual environment and install webssh
RUN /opt/venv/bin/pip install webssh

# Expose the necessary port
EXPOSE 8080

# Set the virtual environment as the default Python environment
ENV PATH="/opt/venv/bin:$PATH"

# Command to run the webssh server
CMD ["wssh", "--address=0.0.0.0", "--port=8080"]
