version: '3'
services:
  wg-easy:
    environment:
      - WG_HOST=pi.jokley.at
      - PASSWORD=jokley82@wireguard
      - WG_DEFAULT_ADDRESS=100.64.0.x
      - WG_DEFAULT_DNS=""
      #- WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_ALLOWED_IPS=100.64.0.1/32
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "1883:1883"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  nginx:
    image: arm64v8/nginx
#    ports:
#      - "80:80"
#      - "443:443"
    restart: unless-stopped                                     
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro
      - ./data/wwwroot:/var/www/root:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro       
      - ./data/certbot/www:/var/www/certbot:ro 
    network_mode: "service:wg-easy"        
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:                                            
    image: certbot/certbot:arm64v8-latest             
    restart: unless-stopped  
    volumes:                                          
      - ./data/certbot/conf:/etc/letsencrypt          
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  webssh:
    build:
      context: ./webssh
    restart: unless-stopped
    container_name: webssh
 #   ports:
 #     - 8080:8080
    network_mode: "service:wg-easy"
